/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "rtl.v:1.1-28.10" *)
module counter_up(clk, rst, count);
  (* src = "rtl.v:24.18-24.27" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0_;
  (* src = "rtl.v:8.11-8.14" *)
  input clk;
  wire clk;
  (* src = "rtl.v:11.28-11.33" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "rtl.v:9.11-9.14" *)
  input rst;
  wire rst;
  assign _0_ = count + (* src = "rtl.v:24.18-24.27" *) 32'd1;
  (* src = "rtl.v:14.1-26.4" *)
  always @(posedge clk)
    if (rst) count <= 4'h0;
    else count <= _0_[3:0];
endmodule
