/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* cells_not_processed =  1  *)
(* src = "rtl.v:1.1-16.10" *)
module counter_down(clk, reset, enable, count);
  (* src = "rtl.v:13.18-13.27" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _0_;
  (* src = "rtl.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "rtl.v:5.22-5.27" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "rtl.v:4.11-4.17" *)
  input enable;
  wire enable;
  (* src = "rtl.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "rtl.v:8.1-14.4" *)
  always @(posedge clk)
    if (reset) count <= 4'hf;
    else if (enable) count <= _0_[3:0];
  assign _0_ = count - (* src = "rtl.v:13.18-13.27" *) 32'd1;
endmodule
