/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl.v:1.1-23.10" *)
module counter_up_down(clk, reset, enable, up_down, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* force_downto = 32'd1 *)
  (* src = "rtl.v:17.22-17.31|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "1 2 3" *)
  wire [3:0] _09_;
  (* force_downto = 32'd1 *)
  (* src = "rtl.v:17.22-17.31|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _10_;
  (* src = "rtl.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "rtl.v:6.22-6.27" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "rtl.v:4.11-4.17" *)
  input enable;
  wire enable;
  (* src = "rtl.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "rtl.v:5.11-5.18" *)
  input up_down;
  wire up_down;
  assign _09_[0] = ~count[0];
  assign _00_ = count[1] ^ up_down;
  assign _10_[1] = _00_ ^ _09_[0];
  assign _01_ = ~(count[2] ^ up_down);
  assign _02_ = up_down | ~(count[1]);
  assign _03_ = count[0] & ~(_00_);
  assign _04_ = _02_ & ~(_03_);
  assign _10_[2] = ~(_04_ ^ _01_);
  assign _05_ = count[3] ^ up_down;
  assign _06_ = up_down | ~(count[2]);
  assign _07_ = _01_ & ~(_04_);
  assign _08_ = _06_ & ~(_07_);
  assign _10_[3] = _08_ ^ _05_;
  (* src = "rtl.v:9.1-21.4" *)
  always @(posedge clk)
    if (reset) count[0] <= 1'h0;
    else if (enable) count[0] <= _09_[0];
  (* src = "rtl.v:9.1-21.4" *)
  always @(posedge clk)
    if (reset) count[1] <= 1'h0;
    else if (enable) count[1] <= _10_[1];
  (* src = "rtl.v:9.1-21.4" *)
  always @(posedge clk)
    if (reset) count[2] <= 1'h0;
    else if (enable) count[2] <= _10_[2];
  (* src = "rtl.v:9.1-21.4" *)
  always @(posedge clk)
    if (reset) count[3] <= 1'h0;
    else if (enable) count[3] <= _10_[3];
  assign _10_[0] = _09_[0];
endmodule
