/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* cells_not_processed =  1  *)
(* src = "rtl.v:1.1-70.10" *)
module basic_fifo(clk, reset, write_en, read_en, data_in, data_out, full, empty);
  (* src = "rtl.v:27.5-68.8" *)
  wire [1:0] _00_;
  (* src = "rtl.v:27.5-68.8" *)
  wire [7:0] _01_;
  (* src = "rtl.v:27.5-68.8" *)
  wire [7:0] _02_;
  (* src = "rtl.v:27.5-68.8" *)
  wire [1:0] _03_;
  (* src = "rtl.v:27.5-68.8" *)
  wire [7:0] _04_;
  (* src = "rtl.v:27.5-68.8" *)
  wire [7:0] _05_;
  (* src = "rtl.v:45.34-45.50" *)
  wire [1:0] _06_;
  (* src = "rtl.v:55.33-55.48" *)
  wire [1:0] _07_;
  (* src = "rtl.v:61.37-61.53" *)
  wire [2:0] _08_;
  wire _09_;
  (* src = "rtl.v:42.21-42.38" *)
  wire _10_;
  (* src = "rtl.v:52.21-52.37" *)
  wire _11_;
  (* src = "rtl.v:39.17-39.34" *)
  wire _12_;
  (* src = "rtl.v:49.17-49.34" *)
  wire _13_;
  (* src = "rtl.v:39.29-39.34" *)
  wire _14_;
  (* src = "rtl.v:49.28-49.34" *)
  wire _15_;
  (* src = "rtl.v:50.29-50.32" *)
  wire [7:0] _16_;
  wire [2:0] _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [1:0] _22_;
  wire [1:0] _23_;
  (* src = "rtl.v:62.37-62.53" *)
  wire [2:0] _24_;
  (* src = "rtl.v:2.18-2.21" *)
  input clk;
  wire clk;
  (* src = "rtl.v:6.18-6.25" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "rtl.v:8.22-8.30" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "rtl.v:10.23-10.28" *)
  output empty;
  wire empty;
  (* src = "rtl.v:9.23-9.27" *)
  output full;
  wire full;
  (* src = "rtl.v:21.15-21.24" *)
  reg [2:0] occupancy;
  (* src = "rtl.v:5.18-5.25" *)
  input read_en;
  wire read_en;
  (* src = "rtl.v:18.15-18.23" *)
  reg [1:0] read_ptr;
  (* src = "rtl.v:3.18-3.23" *)
  input reset;
  wire reset;
  (* src = "rtl.v:4.18-4.26" *)
  input write_en;
  wire write_en;
  (* src = "rtl.v:17.15-17.24" *)
  reg [1:0] write_ptr;
  (* src = "rtl.v:14.15-14.18" *)
  reg [7:0] mem [3:0];
  always @(posedge clk) begin
    if (_02_[7])
      mem[_00_] <= _01_;
  end
  assign _16_ = mem[read_ptr];
  assign _06_ = write_ptr + (* src = "rtl.v:45.34-45.50" *) 1'h1;
  assign _07_ = read_ptr + (* src = "rtl.v:55.33-55.48" *) 1'h1;
  assign _08_ = occupancy + (* src = "rtl.v:61.37-61.53" *) 1'h1;
  (* src = "rtl.v:27.5-68.8" *)
  always @(posedge clk)
    if (reset) occupancy <= 3'h0;
    else if (!_09_) occupancy <= _17_;
  (* src = "rtl.v:27.5-68.8" *)
  always @(posedge clk)
    if (reset) data_out <= 8'h00;
    else if (_13_) data_out <= _16_;
  (* src = "rtl.v:27.5-68.8" *)
  always @(posedge clk)
    if (reset) write_ptr <= 2'h0;
    else if (_12_) write_ptr <= _23_;
  (* src = "rtl.v:27.5-68.8" *)
  always @(posedge clk)
    if (reset) read_ptr <= 2'h0;
    else if (_13_) read_ptr <= _22_;
  assign _09_ = | { _19_, _18_ };
  assign empty = ! (* src = "rtl.v:24.21-24.38" *) occupancy;
  assign full = occupancy == (* src = "rtl.v:25.21-25.38" *) 3'h4;
  assign _10_ = write_ptr == (* src = "rtl.v:42.21-42.38" *) 2'h3;
  assign _11_ = read_ptr == (* src = "rtl.v:52.21-52.37" *) 2'h3;
  assign _13_ = read_en && (* src = "rtl.v:59.39-59.56" *) _15_;
  assign _12_ = write_en && (* src = "rtl.v:59.20-59.37" *) _14_;
  assign _15_ = ! (* src = "rtl.v:59.50-59.56" *) empty;
  assign _14_ = ! (* src = "rtl.v:59.32-59.37" *) full;
  assign _05_[7] = _12_ ? (* full_case = 32'd1 *) (* src = "rtl.v:39.17-39.34|rtl.v:39.13-46.16" *) 1'h1 : 1'h0;
  assign _04_ = _12_ ? (* full_case = 32'd1 *) (* src = "rtl.v:39.17-39.34|rtl.v:39.13-46.16" *) data_in : 8'hxx;
  assign _03_ = _12_ ? (* full_case = 32'd1 *) (* src = "rtl.v:39.17-39.34|rtl.v:39.13-46.16" *) write_ptr : 2'hx;
  function [2:0] _46_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "rtl.v:0.0-0.0|rtl.v:59.13-66.20" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _46_ = b[2:0];
      2'b1?:
        _46_ = b[5:3];
      default:
        _46_ = a;
    endcase
  endfunction
  assign _17_ = _46_(3'hx, { _08_, _24_ }, { _21_, _20_ });
  assign _18_ = ! (* full_case = 32'd1 *) (* src = "rtl.v:0.0-0.0|rtl.v:59.13-66.20" *) { _12_, _13_ };
  assign _19_ = { _12_, _13_ } == (* full_case = 32'd1 *) (* src = "rtl.v:0.0-0.0|rtl.v:59.13-66.20" *) 2'h3;
  assign _20_ = { _12_, _13_ } == (* full_case = 32'd1 *) (* src = "rtl.v:0.0-0.0|rtl.v:59.13-66.20" *) 2'h1;
  assign _21_ = { _12_, _13_ } == (* full_case = 32'd1 *) (* src = "rtl.v:0.0-0.0|rtl.v:59.13-66.20" *) 2'h2;
  assign _02_[7] = reset ? (* full_case = 32'd1 *) (* src = "rtl.v:29.13-29.18|rtl.v:29.9-67.12" *) 1'h0 : _05_[7];
  assign _01_ = reset ? (* full_case = 32'd1 *) (* src = "rtl.v:29.13-29.18|rtl.v:29.9-67.12" *) 8'hxx : _04_;
  assign _00_ = reset ? (* full_case = 32'd1 *) (* src = "rtl.v:29.13-29.18|rtl.v:29.9-67.12" *) 2'hx : _03_;
  assign _22_ = _11_ ? (* full_case = 32'd1 *) (* src = "rtl.v:52.21-52.37|rtl.v:52.17-55.49" *) 2'h0 : _07_;
  assign _23_ = _10_ ? (* full_case = 32'd1 *) (* src = "rtl.v:42.21-42.38|rtl.v:42.17-45.51" *) 2'h0 : _06_;
  assign _24_ = occupancy - (* src = "rtl.v:62.37-62.53" *) 1'h1;
  assign _02_[6:0] = { _02_[7], _02_[7], _02_[7], _02_[7], _02_[7], _02_[7], _02_[7] };
  assign _05_[6:0] = { _05_[7], _05_[7], _05_[7], _05_[7], _05_[7], _05_[7], _05_[7] };
endmodule
