/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl.v:1.1-27.10" *)
module loadable_counter(clk, reset, enable, load, data, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "rtl.v:3.11-3.14" *)
  input clk;
  wire clk;
  (* src = "rtl.v:9.22-9.27" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "rtl.v:7.17-7.21" *)
  input [3:0] data;
  wire [3:0] data;
  (* src = "rtl.v:5.11-5.17" *)
  input enable;
  wire enable;
  (* src = "rtl.v:6.11-6.15" *)
  input load;
  wire load;
  (* src = "rtl.v:4.11-4.16" *)
  input reset;
  wire reset;
  assign _00_ = load | enable;
  assign _01_ = ~count[0];
  assign _07_ = load ? data[0] : _01_;
  assign _02_ = count[1] ^ count[0];
  assign _08_ = load ? data[1] : _02_;
  assign _03_ = ~(count[1] & count[0]);
  assign _04_ = ~(_03_ ^ count[2]);
  assign _09_ = load ? data[2] : _04_;
  assign _05_ = count[2] & ~(_03_);
  assign _06_ = _05_ ^ count[3];
  assign _10_ = load ? data[3] : _06_;
  (* src = "rtl.v:13.1-25.4" *)
  always @(posedge clk)
    if (reset) count[0] <= 1'h0;
    else if (_00_) count[0] <= _07_;
  (* src = "rtl.v:13.1-25.4" *)
  always @(posedge clk)
    if (reset) count[1] <= 1'h0;
    else if (_00_) count[1] <= _08_;
  (* src = "rtl.v:13.1-25.4" *)
  always @(posedge clk)
    if (reset) count[2] <= 1'h0;
    else if (_00_) count[2] <= _09_;
  (* src = "rtl.v:13.1-25.4" *)
  always @(posedge clk)
    if (reset) count[3] <= 1'h0;
    else if (_00_) count[3] <= _10_;
endmodule
