/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl.v:1.1-20.10" *)
module parameterized_counter(clk, reset, enable, count);
  wire _00_;
  wire _01_;
  (* force_downto = 32'd1 *)
  (* src = "rtl.v:17.18-17.27|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _02_;
  (* force_downto = 32'd1 *)
  (* src = "rtl.v:17.18-17.27|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _03_;
  (* src = "rtl.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "rtl.v:8.28-8.33" *)
  output [3:0] count;
  reg [3:0] count;
  (* src = "rtl.v:6.11-6.17" *)
  input enable;
  wire enable;
  (* src = "rtl.v:5.11-5.16" *)
  input reset;
  wire reset;
  assign _02_[0] = ~count[0];
  assign _03_[1] = count[1] ^ count[0];
  assign _00_ = ~(count[1] & count[0]);
  assign _03_[2] = ~(_00_ ^ count[2]);
  assign _01_ = count[2] & ~(_00_);
  assign _03_[3] = _01_ ^ count[3];
  (* src = "rtl.v:11.1-18.4" *)
  always @(posedge clk)
    if (reset) count[3] <= 1'h0;
    else if (enable) count[3] <= _03_[3];
  (* src = "rtl.v:11.1-18.4" *)
  always @(posedge clk)
    if (reset) count[0] <= 1'h0;
    else if (enable) count[0] <= _02_[0];
  (* src = "rtl.v:11.1-18.4" *)
  always @(posedge clk)
    if (reset) count[1] <= 1'h0;
    else if (enable) count[1] <= _03_[1];
  (* src = "rtl.v:11.1-18.4" *)
  always @(posedge clk)
    if (reset) count[2] <= 1'h0;
    else if (enable) count[2] <= _03_[2];
  assign _02_[3:1] = count[3:1];
  assign _03_[0] = _02_[0];
endmodule
